version: '3.5'
services:
  database:
    container_name: postgres2
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql_2

volumes:
  db_volume:
